# Generated by Django 3.0.4 on 2020-05-29 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='product_id',
        ),
    ]
